# Generated by Django 5.2.17 on 2026-09-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale_sessions', '0010_employee_password_employee_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAuthToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='المفتاح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='sale_sessions.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'رمز دخول',
                'verbose_name_plural': 'رموز الدخول',
            },
        ),
    ]
