# Generated by Django 5.2.17 on 2026-09-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('suppliers', '0005_fabric_min_stock_alter_fabric_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الموظف')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفتح')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_sessions', to='branches.branch', verbose_name='الفرع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sale_sessions.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'جلسة بيع',
                'verbose_name_plural': 'جلسات البيع',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('sale_type', models.CharField(choices=[('yard', 'ياردات'), ('roll', 'لفات')], default='yard', max_length=10, verbose_name='نوع البيع')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='سعر الوحدة')),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('transfer', 'تحويل'), ('card', 'ماكينة')], default='cash', max_length=10, verbose_name='طريقة الدفع')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الإجمالي')),
                ('sale_date', models.DateField(verbose_name='تاريخ البيع')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_items', to='suppliers.fabric', verbose_name='القماش')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale_sessions.salesession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'بند جلسة',
                'verbose_name_plural': 'بنود الجلسة',
                'ordering': ['-id'],
            },
        ),
    ]
