# Generated by Django 5.2.17 on 2026-09-13 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesession',
            options={'ordering': ['-opened_at'], 'verbose_name': 'وردية بيع', 'verbose_name_plural': 'ورديات البيع'},
        ),
        migrations.AlterModelOptions(
            name='salesessionitem',
            options={'ordering': ['-id'], 'verbose_name': 'بند وردية', 'verbose_name_plural': 'بنود الوردية'},
        ),
        migrations.AlterField(
            model_name='salesessionitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale_sessions.salesession', verbose_name='الوردية'),
        ),
    ]
