# Generated by Django 5.2.17 on 2026-09-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0002_alter_salesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hidden_sections',
            field=models.JSONField(blank=True, default=list, verbose_name='الأقسام المخفية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='الصلاحيات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('supervisor', 'مشرف'), ('sales', 'مندوب مبيعات'), ('viewer', 'مشاهد'), ('custom', 'مخصص')], default='admin', max_length=20, verbose_name='الدور'),
        ),
    ]
