# Generated by Django 5.2.17 on 2026-09-13 21:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0003_employee_hidden_sections_employee_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesessionitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قيمة الخصم'),
        ),
    ]
