# Generated by Django 5.2.17 on 2026-09-15 18:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0004_session_item_discount_move_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_active',
            field=models.BooleanField(default=False, verbose_name='تفعيل العمولة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة العمولة (%)'),
        ),
        migrations.AddField(
            model_name='salesession',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='قيمة العمولة'),
        ),
    ]
