# Generated by Django 5.2.17 on 2026-09-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0005_employee_commission_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('supervisor', 'مشرف'), ('sales', 'مندوب مبيعات'), ('accountant', 'محاسب'), ('viewer', 'مشاهد'), ('custom', 'مخصص')], default='admin', max_length=20, verbose_name='الدور'),
        ),
    ]
