# Generated by Django 5.2.17 on 2026-09-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0006_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesessionitem',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم الزبون'),
        ),
        migrations.AddField(
            model_name='salesessionitem',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم هاتف الزبون'),
        ),
    ]
