# Generated by Django 5.2.17 on 2026-09-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0007_salesessionitem_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesessionitem',
            name='sale_group',
            field=models.CharField(blank=True, max_length=36, verbose_name='معرّف البيعة'),
        ),
    ]
