# Generated by Django 5.2.17 on 2026-09-16 21:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0008_salesessionitem_sale_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesession',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='وردية مُدخلة يدوياً'),
        ),
        migrations.AddField(
            model_name='salesession',
            name='manual_card',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الماكينة (يدوي)'),
        ),
        migrations.AddField(
            model_name='salesession',
            name='manual_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='النقدي (يدوي)'),
        ),
        migrations.AddField(
            model_name='salesession',
            name='manual_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البيعة اليدوية'),
        ),
        migrations.AddField(
            model_name='salesession',
            name='manual_transfer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='التحويل (يدوي)'),
        ),
    ]
