# Generated by Django 5.2.17 on 2026-09-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0009_salesession_is_manual_salesession_manual_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='كلمة المرور'),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='اسم المستخدم'),
        ),
    ]
