# Generated by Django 5.2.17 on 2026-09-20 19:18
#
# ملاحظة: الأعمدة التالية موجودة فعلياً في قاعدة البيانات الحية (أُضيفت خارج
# الهجرات سابقاً). لذلك يستخدم EF IF NOT EXISTS ليتجاوز هذه الأعمدة في القواعد
# الحية، بينما ينشئها من جديد في أي قاعدة جديدة (مثل قاعدة بيانات الاختبار)
# ويُسجِّل الحقول في حالة Django عبر state_operations.

from django.db import migrations, models

_ADD = """
ALTER TABLE sale_sessions_employee ADD COLUMN IF NOT EXISTS {col} {dtype};
"""

_DROP = """
ALTER TABLE sale_sessions_employee DROP COLUMN IF EXISTS {col};
"""


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0011_provision_employee_users'),
    ]

    operations = [
        migrations.RunSQL(
            sql="".join([
                _ADD.format(col='"department"', dtype="varchar(100) NOT NULL DEFAULT ''"),
                _ADD.format(col='"position"', dtype="varchar(100) NOT NULL DEFAULT ''"),
                _ADD.format(col='"email"', dtype="varchar(254) NOT NULL DEFAULT ''"),
                _ADD.format(col='"employee_code"', dtype="varchar(50) NULL"),
                _ADD.format(col='"multi_branch_access"', dtype="boolean NOT NULL DEFAULT false"),
                _ADD.format(col='"must_change_password"', dtype="boolean NOT NULL DEFAULT false"),
            ]),
            reverse_sql="".join([
                _DROP.format(col='"department"'),
                _DROP.format(col='"position"'),
                _DROP.format(col='"email"'),
                _DROP.format(col='"employee_code"'),
                _DROP.format(col='"multi_branch_access"'),
                _DROP.format(col='"must_change_password"'),
            ]),
            state_operations=[
                migrations.AddField(
                    model_name='employee',
                    name='department',
                    field=models.CharField(blank=True, default='', max_length=100, verbose_name='القسم'),
                ),
                migrations.AddField(
                    model_name='employee',
                    name='email',
                    field=models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني'),
                ),
                migrations.AddField(
                    model_name='employee',
                    name='employee_code',
                    field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='رقم الموظف'),
                ),
                migrations.AddField(
                    model_name='employee',
                    name='multi_branch_access',
                    field=models.BooleanField(default=False, verbose_name='دخول متعدد الفروع'),
                ),
                migrations.AddField(
                    model_name='employee',
                    name='must_change_password',
                    field=models.BooleanField(default=False, verbose_name='تغيير كلمة المرور عند أول دخول'),
                ),
                migrations.AddField(
                    model_name='employee',
                    name='position',
                    field=models.CharField(blank=True, default='', max_length=100, verbose_name='المسمى الوظيفي'),
                ),
            ],
        ),
    ]