# Generated by Django 5.2.17 on 2026-09-21 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_monthly_sales_target_fabricbranchprice'),
        ('sale_sessions', '0012_employee_department_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='civil_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الرقم المدني / الهوية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='اختياري للمدير والمشرف', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branches.branch', verbose_name='الفرع'),
        ),
    ]
