# Generated by Django 6.1.1 on 2026-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0014_employee_state_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='الأفاتار'),
        ),
    ]
