# Generated by Django 5.2.17 on 2026-09-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0015_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesessionitem',
            name='sale_type',
            field=models.CharField(choices=[('yard', 'ياردات'), ('roll', 'طاقات')], default='yard', max_length=10, verbose_name='نوع البيع'),
        ),
    ]
