# Generated by Django 6.1.1 on 2026-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_monthly_sales_target_fabricbranchprice'),
        ('sale_sessions', '0016_alter_salesessionitem_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_branches',
            field=models.ManyToManyField(blank=True, help_text='فروع إضافية يرى الموظف بياناتها بجانب فرعه الأساسي', related_name='employees_allowed', to='branches.branch', verbose_name='الفروع المسموحة'),
        ),
    ]
