# Generated by Django 5.2.17 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0017_employee_allowed_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='يُحدَّث عند أي طلب؛ المتصل من ظهر خلال آخر دقيقتين', null=True, verbose_name='آخر ظهور'),
        ),
    ]