# Generated by Django 6.1.1 on 2026-09-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0018_employee_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesessionitem',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='مسترجع'),
        ),
        migrations.AddField(
            model_name='salesessionitem',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='سبب الاسترجاع'),
        ),
        migrations.AddField(
            model_name='salesessionitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الاسترجاع'),
        ),
    ]
