# Generated by Django 6.1.1 on 2026-09-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0019_salesessionitem_is_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar_image',
            field=models.TextField(blank=True, default='', help_text='صورة مرفوعة من الجهاز كـ data:image/...;base64 — تُعرض بدل الأفاتار عندما تكون موجودة. تقبّلها فقط AccountAvatarView بحجم محدود ومُتحقَّق.', verbose_name='الصورة الشخصية'),
        ),
    ]
