# Generated by Django 6.1.1 on 2026-09-24 14:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0020_employee_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesessionitem',
            name='card_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مبلغ عمولة الماكينة المخصوم (يُحسب تلقائياً من إعدادات النظام)', max_digits=15, verbose_name='رسوم الماكينة'),
        ),
        migrations.AddField(
            model_name='salesessionitem',
            name='card_type',
            field=models.CharField(blank=True, choices=[('credit', 'إئتماني'), ('debit', 'خصم مباشر')], default='', help_text='نوع الماكينة عند الدفع بها: إئتماني أو خصم مباشر (كل نوع بنسبة عمولة مستقلة)', max_length=10, verbose_name='نوع البطاقة'),
        ),
        migrations.AddField(
            model_name='salesessionitem',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='إجمالي البند بعد خصم رسوم الماكينة (يساوي الإجمالي عند الدفع نقداً أو تحويلاً)', max_digits=15, verbose_name='صافي البند'),
        ),
    ]
