# Generated by Django 5.2.17 on 2026-09-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0021_salesessionitem_card_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesession',
            name='session_date',
            field=models.DateField(blank=True, help_text='التاريخ المحاسبي الذي تُسجَّل عليه مبيعات الوردية؛ فارغ = يُحسب تلقائياً من وقت البيع', null=True, verbose_name='تاريخ الوردية'),
        ),
        migrations.AlterField(
            model_name='salesessionitem',
            name='card_type',
            field=models.CharField(blank=True, choices=[('credit', 'إئتماني / Credit'), ('debit', 'خصم مباشر / Debit')], default='', help_text='نوع الماكينة عند الدفع بها: إئتماني أو خصم مباشر (كل نوع بنسبة عمولة مستقلة)', max_length=10, verbose_name='نوع البطاقة'),
        ),
    ]
