# Generated by Django 6.1.1 on 2026-09-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0025_audit_section_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_tracked',
            field=models.BooleanField(default=False, help_text='عند التفعيل تُحتسب أيام الحضور والغياب وساعات العمل الإضافي من الورديات وقت توليد مسيّر الرواتب', verbose_name='احتساب الحضور تلقائياً'),
        ),
    ]
