# Generated by Django 5.2.17 on 2026-09-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0028_salesessionitem_group_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='الثيم المفضل'),
        ),
    ]
