# Generated by Django 5.2.17 on 2026-09-11 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(default='القماش العربي', max_length=200, verbose_name='اسم النشاط')),
                ('business_phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('business_address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('currency_symbol', models.CharField(default='ر.ع', max_length=10, verbose_name='رمز العملة')),
                ('currency_code', models.CharField(default='OMR', max_length=10, verbose_name='كود العملة')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='منازل الفاصلة العشرية')),
                ('default_period', models.CharField(choices=[('today', 'اليوم'), ('week', 'هذا الأسبوع'), ('month', 'هذا الشهر')], default='today', max_length=20, verbose_name='الفترة الافتراضية للوحة التحكم')),
                ('default_page_size', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='عدد الصفوف في الجداول')),
                ('hidden_sections', models.JSONField(blank=True, default=list, verbose_name='الأقسام المخفية')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
