# Generated by Django 5.2.17 on 2026-09-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, help_text='عند التفعيل يُسمح بتسجيل مبيعات تتجاوز رصيد المخزون المتاح', verbose_name='السماح بالمبيعات برصيد سالب'),
        ),
    ]
