# Generated by Django 5.2.17 on 2026-09-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0002_appsettings_allow_negative_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='date_format',
            field=models.CharField(choices=[('YYYY-MM-DD', '2026-09-13'), ('DD-MM-YYYY', '13-09-2026'), ('DD/MM/YYYY', '13/09/2026'), ('MM-DD-YYYY', '09-13-2026')], default='YYYY-MM-DD', max_length=20, verbose_name='صيغة التاريخ'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_theme',
            field=models.CharField(choices=[('emerald', 'زمردي'), ('amber', 'ذهبي'), ('blue', 'أزرق'), ('violet', 'بنفسجي'), ('rose', 'وردي'), ('slate', 'رمادي')], default='emerald', max_length=20, verbose_name='المظهر الافتراضي'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=50, help_text='تنبيه عند وصول رصيد القماش إلى هذا الحد أو أقل', max_digits=12, verbose_name='حد تنبيه المخزون المنخفض'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='receipt_footer',
            field=models.CharField(blank=True, help_text='نص يظهر أسفل الفواتير المطبوعة', max_length=255, verbose_name='تذييل الفواتير والطباعة'),
        ),
    ]
