# Generated by Django 5.2.17 on 2026-09-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0003_appsettings_business_email_appsettings_date_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='default_theme',
            field=models.CharField(choices=[('green', 'أخضر'), ('blue', 'أزرق'), ('violet', 'بنفسجي'), ('rose', 'وردي'), ('amber', 'ذهبي')], default='green', max_length=20, verbose_name='المظهر الافتراضي'),
        ),
    ]
