# Generated by Django 5.2.17 on 2026-09-13 22:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0004_fix_default_theme_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='currency_position',
            field=models.CharField(choices=[('after', 'بعد المبلغ'), ('before', 'قبل المبلغ')], default='after', max_length=10, verbose_name='موضع رمز العملة'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('transfer', 'تحويل'), ('card', 'ماكينة')], default='cash', help_text='تُحدَّد تلقائياً عند إضافة بند جديد للوردية', max_length=10, verbose_name='طريقة الدفع الافتراضية'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='discount_max_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='الحد الأقصى لخصم البند كنسبة من إجماليه (100 تعني بدون حد)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='أقصى خصم مسموح (%)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='', help_text='حروف تُسبَق لرقم الإيصال المطبوع (مثال: INV-)', max_length=30, verbose_name='برفكس أرقام الإيصالات'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='low_stock_alert_enabled',
            field=models.BooleanField(default=True, help_text='إظهار تنبيهات الأقمشة التي وصل رصيدها إلى حد التنبيه', verbose_name='تفعيل تنبيهات المخزون المنخفض'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='previous_day_cutoff_hour',
            field=models.PositiveSmallIntegerField(default=2, help_text='البيوع المسجلة قبل هذه الساعة تُعدّ لليوم السابق (افتراضياً 2 صباحاً)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='ساعة بداية اليوم المحاسبي'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='receipt_show_phone',
            field=models.BooleanField(default=True, verbose_name='إظهار رقم الهاتف في الإيصال المطبوع'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='receipt_show_tax',
            field=models.BooleanField(default=False, verbose_name='إظهار الضريبة في الإيصال المطبوع'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='session_danger_hours',
            field=models.PositiveSmallIntegerField(default=4, help_text='بعد هذه المدة تظهر شارة تحذير حمراء للوردية المفتوحة', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)], verbose_name='تحذير الوردية الطويلة (ساعات)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='session_warn_hours',
            field=models.PositiveSmallIntegerField(default=2, help_text='بعد هذه المدة تظهر شارة تحذير على الوردية المفتوحة', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='تنبيه مدة الوردية (ساعات)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='تُحسب على إجمالي الإيصال المطبوع عند تفعيل إظهار الضريبة', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='نسبة الضريبة المضافة (%)'),
        ),
    ]
