# Generated by Django 5.2.17 on 2026-09-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0005_expand_control_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='logo',
            field=models.CharField(blank=True, default='', help_text='مسار ملف صورة الشعار (PNG) داخل مجلد الوسائط', max_length=255, verbose_name='شعار الموقع'),
        ),
    ]
