# Generated by Django 5.2.17 on 2026-09-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0007_default_payment_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='commercial_registration',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='invoice_notes',
            field=models.CharField(blank=True, help_text='نص اختياري يظهر أعلى خانتي التوقيع في الفاتورة', max_length=255, verbose_name='ملاحظات الفاتورة'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='trade_name',
            field=models.CharField(blank=True, help_text='الاسم التجاري المسجّل (اسم السجل التجاري) كما يظهر في الفواتير', max_length=200, verbose_name='الاسم التجاري'),
        ),
    ]
