# Generated by Django 5.2.17 on 2026-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0008_appsettings_commercial_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='default_theme',
            field=models.CharField(choices=[('green', 'أخضر'), ('blue', 'أزرق'), ('violet', 'بنفسجي'), ('rose', 'وردي'), ('amber', 'ذهبي'), ('cyan', 'سماوي'), ('orange', 'برتقالي'), ('red', 'أحمر'), ('pink', 'زهري'), ('indigo', 'نيلي'), ('teal', 'أخضر مائي'), ('fuchsia', 'فوشيا'), ('lime', 'ليموني'), ('slate', 'رمادي أردوازي'), ('maroon', 'نبيذي'), ('burgundy', 'برغندي'), ('lilac', 'ليلكي'), ('forest', 'أخضر غابة'), ('plum', 'خوخي داكن'), ('navy', 'كحلي')], default='green', max_length=20, verbose_name='المظهر الافتراضي'),
        ),
    ]
