# Generated by Django 5.2.17 on 2026-09-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0009_alter_appsettings_default_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='backup_password',
            field=models.CharField(blank=True, default='', help_text='عند ضبطها تُشفَّر النسخ الاحتياطية وتتطلب كلمة المرور نفسها للاستعادة', max_length=128, verbose_name='كلمة مرور النسخ الاحتياطي'),
        ),
    ]
