# Generated by Django 6.1.1 on 2026-09-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0010_appsettings_backup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='font_family',
            field=models.CharField(choices=[('cairo', 'Cairo'), ('ibm', 'IBM Plex Sans Arabic'), ('amiri', 'Amiri'), ('noto', 'Noto Sans Arabic')], default='cairo', help_text='الخط الافتراضي للأجهزة الجديدة — كل مستخدم يمكنه تغيير خطه وحجمه لنفسه', max_length=20, verbose_name='نوع الخط الافتراضي'),
        ),
    ]
