# Generated by Django 6.1.1 on 2026-09-22 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0011_appsettings_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=False, help_text='عند التفعيل تُنشأ نسخة احتياطية تلقائياً حسب الجدول الزمني أدناه', verbose_name='تفعيل النسخ الاحتياطي التلقائي'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_backup_every_hours',
            field=models.PositiveIntegerField(default=0, help_text='0 = إيقاف الفاصل الزمني (يعمل بالوقت اليومي فقط). مثال: 6 تعني نسخة كل 6 ساعات', validators=[django.core.validators.MaxValueValidator(720)], verbose_name='نسخ احتياطي كل (ساعة)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_backup_time',
            field=models.TimeField(blank=True, help_text='نشهر عند أداة المجدول (Cron / Task Scheduler) في هذا الوقت يومياً، كبديل عن الفاصل الزمني', null=True, verbose_name='وقت النسخ التلقائي اليومي'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_auto_backup_at',
            field=models.DateTimeField(blank=True, help_text='يُحدَّث تلقائياً عند نجاح النسخة التلقائية', null=True, verbose_name='آخر نسخة تلقائية'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_auto_backup_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='مسار آخر نسخة تلقائية'),
        ),
    ]
