# Generated by Django 6.1.1 on 2026-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0012_appsettings_auto_backup_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='font_family',
            field=models.CharField(choices=[('cairo', 'Cairo'), ('ibm', 'IBM Plex Sans Arabic'), ('amiri', 'Amiri'), ('noto', 'Noto Sans Arabic'), ('almarai', 'Almarai'), ('tajawal', 'Tajawal'), ('rubik', 'Rubik'), ('changa', 'Changa'), ('mada', 'Mada')], default='cairo', help_text='الخط الافتراضي للأجهزة الجديدة — كل مستخدم يمكنه تغيير خطه وحجمه لنفسه', max_length=20, verbose_name='نوع الخط الافتراضي'),
        ),
    ]
