# Generated by Django 6.1.1 on 2026-09-24 15:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0013_alter_appsettings_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='card_credit_fee_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='النسبة المخصومة من مبيعات الماكينة عند اختيار نوع إئتماني', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='نسبة عمولة الماكينة الإئتمانية (%)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='card_debit_fee_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='النسبة المخصومة من مبيعات الماكينة عند اختيار نوع خصم مباشر', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='نسبة عمولة الماكينة الخصم المباشر (%)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('transfer', 'تحويل'), ('card', 'ماكينة')], default='transfer', help_text='تستخدم عند إنشاء بند بيع جديد ثم يمكن تغييرها لكل بند', max_length=10, verbose_name='طريقة الدفع الافتراضية'),
        ),
    ]
