# Generated by Django 5.2.17 on 2026-09-27 08:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0014_appsettings_card_credit_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='min_sale_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('85'), help_text='يُعبأ الحد الأدنى لسعر بيع الياردة تلقائياً بهذه النسبة من سعر البيع (افتراضياً 85%) — وتبقى القيمة قابلة للتعديل', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='الحد الأدنى للبيع كنسبة من سعر البيع (%)'),
        ),
    ]
