# Generated by Django 5.2.17 on 2026-09-27 08:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def set_default_min_sale_percent(apps, schema_editor):
    AppSettings = apps.get_model("appsettings", "AppSettings")
    AppSettings.objects.update(min_sale_percent=Decimal("15"))


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0015_appsettings_min_sale_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='min_sale_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='يُعبأ الحد الأدنى لسعر بيع الياردة تلقائياً بهذه النسبة من سعر البيع (افتراضياً 15%) — وتبقى القيمة قابلة للتعديل', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='الحد الأدنى للبيع كنسبة من سعر البيع (%)'),
        ),
        migrations.RunPython(set_default_min_sale_percent, migrations.RunPython.noop),
    ]
