# Generated by Django 5.2.17 on 2026-09-27 08:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0016_alter_appsettings_min_sale_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='min_piece_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='يُرفض البيع نهائياً إذا كان سعر القطعة النهائي أقل من سعر الشراء مضروباً في هذا العدد — ضع 0 لإيقاف الميزة (مثال: 1 = ضعف واحد، 1.5 = ضعف ونصف، 2 = ضعفان)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='الحد الأدنى لسعر القطعة (ضعف من سعر الشراء)'),
        ),
    ]
