# Generated by Django 6.1.1 on 2026-09-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0017_appsettings_min_piece_price_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='backup_password',
            field=models.CharField(blank=True, default='', help_text='مفتاح تشفير النسخ الاحتياطية (AES-256-GCM). التشفير إلزامي: ما لم تُضبط تُرفض النسخ بدل تصديرها مقروءة. الكلمة نفسها تُطلب عند الاستعادة، وتغييرها لا يفتح النسخ السابقة', max_length=128, verbose_name='كلمة مرور النسخ الاحتياطي'),
        ),
    ]
