# Generated by Django 5.2.17 on 2026-10-04 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0018_alter_appsettings_backup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='session_auto_close_enabled',
            field=models.BooleanField(default=True, help_text='عند بلوغ الموعد تغلق النظام الورديات التي تجاوزته ولا تزال مفتوحة', verbose_name='إغلاق الورديات المنسية تلقائياً'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='session_auto_close_time',
            field=models.TimeField(default=datetime.time(2, 0), help_text='أول موعد لهذا الوقت بعد فتح الوردية؛ إن بقت مفتوحة عنده أغلقها النظام وحدّث مبيعاتها على يوم فتحها', verbose_name='موعد إغلاق الوردية المنسية'),
        ),
    ]
