# Generated by Django 5.2.17 on 2026-09-16 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('period_end', models.DateField(unique=True, verbose_name='أخر يوم في الفترة المغلقة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='صافي أرباح الفترة')),
            ],
            options={
                'verbose_name': 'فترة مقفلة',
                'verbose_name_plural': 'الفترات المغلقة',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الحساب')),
                ('type', models.CharField(choices=[('asset', 'أصل'), ('liability', 'التزام'), ('equity', 'حقوق ملكية'), ('income', 'إيراد'), ('expense', 'مصروف')], max_length=10, verbose_name='النوع')),
                ('source_key', models.CharField(blank=True, help_text='يربط الحساب تلقائياً بمصدر خارجي (تصنيف مصروف، طريقة دفع...)', max_length=80, null=True, unique=True, verbose_name='مفتاح المصدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, verbose_name='حساب نظامي')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='البيان')),
                ('source', models.CharField(choices=[('manual', 'قيد يدوي'), ('session', 'إغلاق وردية بيع'), ('purchase', 'عمليات الموردين'), ('expense', 'مصروف'), ('partner', 'عملية شريك'), ('closing', 'قيد إقفال دوري')], default='manual', max_length=15, verbose_name='المصدر')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف المصدر')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'القيود اليومية',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='دائن')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='البيان')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='الحساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'أسطر القيد',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source', 'source_id'], name='accounting__source_7c7de7_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='accounting__date_e3f521_idx'),
        ),
    ]
