# Generated by Django 5.2.17 on 2026-09-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'قيد يدوي'), ('session', 'إغلاق وردية بيع'), ('purchase', 'عمليات الموردين'), ('expense', 'مصروف'), ('partner', 'عملية شريك'), ('closing', 'قيد إقفال دوري'), ('payroll', 'مسيّر رواتب'), ('salary_advance', 'سلفة راتب')], default='manual', max_length=15, verbose_name='المصدر'),
        ),
    ]
