# Generated by Django 5.2.17 on 2026-10-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False, verbose_name='موافقة رسائل واتساب'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت موافقة واتساب'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إلغاء موافقة واتساب'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_welcome_error',
            field=models.CharField(blank=True, max_length=500, verbose_name='خطأ إرسال رسالة واتساب'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_welcome_message_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='معرف رسالة واتساب'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_welcome_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال رسالة الترحيب'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_welcome_status',
            field=models.CharField(choices=[('not_requested', 'لم يُطلب الإرسال'), ('not_configured', 'التكامل غير مهيأ'), ('sent', 'أُرسل إلى واتساب'), ('failed', 'تعذر الإرسال')], default='not_requested', max_length=20, verbose_name='حالة رسالة الترحيب عبر واتساب'),
        ),
    ]
