-- ============================================================================
-- القماش العربي - نظام إدارة أعمال الأقمشة - مخطط قاعدة البيانات
-- Al Qomash Al Arabi - Fabric Business Management - Database Schema
-- Engine: PostgreSQL 17+ | Charset: UTF8 (Arabic)
-- This schema is the reference DDL for the Phase 1 (MVP) build.
-- In normal operation the schema is managed by Django migrations
-- (python manage.py migrate). This file is provided for reference /
-- manual provisioning outside Django.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- Branch: الفروع
-- ----------------------------------------------------------------------------
CREATE TABLE "branches_branch" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "is_active" boolean NOT NULL,
    "name" varchar(150) NOT NULL,
    "code" varchar(30) NOT NULL UNIQUE,
    "phone" varchar(30) NOT NULL,
    "address" varchar(255) NOT NULL,
    "city" varchar(100) NOT NULL,
    "notes" text NOT NULL
);
CREATE INDEX "branches_branch_code_53bf2843_like" ON "branches_branch" ("code" varchar_pattern_ops);

-- ----------------------------------------------------------------------------
-- Supplier: الموردون
-- ----------------------------------------------------------------------------
CREATE TABLE "suppliers_supplier" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "is_active" boolean NOT NULL,
    "name" varchar(150) NOT NULL,
    "company_name" varchar(200) NOT NULL,
    "phone" varchar(30) NOT NULL,
    "email" varchar(254) NOT NULL,
    "address" varchar(255) NOT NULL,
    "city" varchar(100) NOT NULL,
    "country" varchar(100) NOT NULL,
    "tax_number" varchar(50) NOT NULL,
    "notes" text NOT NULL
);

-- ----------------------------------------------------------------------------
-- DailySale: المبيعات اليومية (سجل واحد لكل فرع لكل يوم)
-- ----------------------------------------------------------------------------
CREATE TABLE "sales_dailysale" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "date" date NOT NULL,
    "total_sales" numeric(15, 2) NOT NULL,
    "cash_amount" numeric(15, 2) NOT NULL,
    "transfer_amount" numeric(15, 2) NOT NULL,
    "card_amount" numeric(15, 2) NOT NULL,
    "other_amount" numeric(15, 2) NOT NULL,
    "notes" text NOT NULL,
    "branch_id" bigint NOT NULL,
    CONSTRAINT "unique_branch_date_sale" UNIQUE ("branch_id", "date"),
    CONSTRAINT "sales_dailysale_branch_id_bf7fec1d_fk_branches_branch_id"
        FOREIGN KEY ("branch_id") REFERENCES "branches_branch" ("id")
        DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX "sales_dailysale_branch_id_bf7fec1d" ON "sales_dailysale" ("branch_id");
CREATE INDEX "sales_daily_branch__922644_idx" ON "sales_dailysale" ("branch_id", "date");
CREATE INDEX "sales_daily_date_f117eb_idx" ON "sales_dailysale" ("date");

-- ----------------------------------------------------------------------------
-- ExpenseCategory: تصنيفات المصاريف
-- ----------------------------------------------------------------------------
CREATE TABLE "expenses_expensecategory" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "is_active" boolean NOT NULL,
    "name" varchar(120) NOT NULL,
    "code" varchar(30) NOT NULL UNIQUE,
    "is_system" boolean NOT NULL,
    "notes" varchar(255) NOT NULL
);
CREATE INDEX "expenses_expensecategory_code_9b624ba3_like" ON "expenses_expensecategory" ("code" varchar_pattern_ops);

-- ----------------------------------------------------------------------------
-- Expense: المصاريف
-- ----------------------------------------------------------------------------
CREATE TABLE "expenses_expense" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "date" date NOT NULL,
    "amount" numeric(15, 2) NOT NULL,
    "payment_method" varchar(10) NOT NULL,
    "description" varchar(255) NOT NULL,
    "notes" text NOT NULL,
    "branch_id" bigint NOT NULL,
    "category_id" bigint NOT NULL,
    CONSTRAINT "expenses_expense_branch_id_8a762cc5_fk_branches_branch_id"
        FOREIGN KEY ("branch_id") REFERENCES "branches_branch" ("id")
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "expenses_expense_category_id_aa33bbdd_fk_expenses_"
        FOREIGN KEY ("category_id") REFERENCES "expenses_expensecategory" ("id")
        DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX "expenses_expense_branch_id_8a762cc5" ON "expenses_expense" ("branch_id");
CREATE INDEX "expenses_expense_category_id_aa33bbdd" ON "expenses_expense" ("category_id");
CREATE INDEX "expenses_ex_branch__c0e291_idx" ON "expenses_expense" ("branch_id", "date");
CREATE INDEX "expenses_ex_categor_9e3535_idx" ON "expenses_expense" ("category_id", "date");

COMMIT;