# Generated by Django 5.2.17 on 2026-09-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي المبيعات')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبيعات النقدية')),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبيعات التحويل')),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبيعات البطاقة')),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبيعات أخرى')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'مبيعات يومية',
                'verbose_name_plural': 'المبيعات اليومية',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'date'], name='sales_daily_branch__922644_idx'), models.Index(fields=['date'], name='sales_daily_date_f117eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'date'), name='unique_branch_date_sale')],
            },
        ),
    ]
