# Generated by Django 5.2.17 on 2026-09-12 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('suppliers', '0005_fabric_min_stock_alter_fabric_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('yards', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ياردات المبيعات')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='suppliers.fabric', verbose_name='القماش')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sales.dailysale', verbose_name='البيع')),
            ],
            options={
                'verbose_name': 'صنف مبيعات',
                'verbose_name_plural': 'أصناف المبيعات',
                'ordering': ['id'],
            },
        ),
    ]
