# Generated by Django 5.2.17 on 2026-09-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0001_initial'),
        ('sales', '0002_dailysaleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sales', to='sale_sessions.employee', verbose_name='الموظف'),
        ),
    ]
