# Generated by Django 5.2.17 on 2026-09-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_dailysale_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaleitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='سعر الياردة عند البيع (اختياري)', max_digits=12, null=True, verbose_name='سعر الوحدة'),
        ),
    ]
