# Generated by Django 6.1.1 on 2026-10-01 06:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale_sessions', '0029_employee_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='عند التفعيل يُفتح سجل الحضور تلقائياً مع كل دخول ويغلق مع كل خروج', verbose_name='تفعيل تسجيل الحضور')),
                ('login_window_start', models.TimeField(default='07:00', help_text='قبل هذه الساعة يُعدّ الدخول مبكراً (قبل الدوام)', verbose_name='بداية نافذة الدخول')),
                ('login_window_end', models.TimeField(default='09:00', help_text='بعد هذه الساعة يُحتسب دخولٌ متأخّر', verbose_name='نهاية نافذة الدخول')),
                ('logout_window_start', models.TimeField(default='16:00', help_text='قبل هذه الساعة يُحتسب خروجٌ مبكر', verbose_name='بداية نافذة الخروج')),
                ('logout_window_end', models.TimeField(default='18:00', help_text='بعد هذه الساعة يُحتسب العمل إضافياً من لحظة بداية نافذة الخروج', verbose_name='نهاية نافذة الخروج')),
                ('workday_minutes', models.PositiveIntegerField(default=480, help_text='ما بعده من دقائق اليوم يُحتسب عملاً إضافياً (افتراضياً 480 دقيقة = 8 ساعات)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='طول يوم العمل (دقائق)')),
                ('grace_minutes', models.PositiveIntegerField(default=5, help_text='لا يُحتسب تأخيرٌ حتى يتجاوز هذا العدد من الدقائق', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='سماح التأخير (دقائق)')),
                ('day_cutoff_hour', models.PositiveSmallIntegerField(default=3, help_text='دخولٌ بعد منتصف الليل قبل هذه الساعة يُنسب لليوم السابق (افتراضياً 3 صباحاً)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='ساعة بداية اليوم')),
                ('weekend_days', models.JSONField(blank=True, default=list, help_text='أرقام الأيام: 0 الاثنين .. 6 الجمعة. الافتراضي الجمعة', verbose_name='أيام العطلة الأسبوعية')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سياسة الحضور',
                'verbose_name_plural': 'سياسات الحضور',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('login_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الدخول')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('worked_minutes', models.IntegerField(blank=True, null=True, verbose_name='ساعات العمل (دقائق)')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='التأخير (دقائق)')),
                ('early_leave_minutes', models.IntegerField(default=0, verbose_name='الانصراف المبكر (دقائق)')),
                ('overtime_minutes', models.IntegerField(default=0, verbose_name='الإضافي (دقائق)')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('early_leave', 'انصراف مبكر'), ('absent', 'غائب'), ('excused', 'مبرر'), ('inside', 'داخل الدوام'), ('off', 'عطلة')], default='absent', max_length=20, verbose_name='الحالة')),
                ('excuse', models.CharField(choices=[('none', 'لا شيء'), ('sick', 'مريض'), ('leave', 'إجازة'), ('official', 'مهمة رسمية'), ('other', 'أخرى')], default='none', max_length=20, verbose_name='المبرر')),
                ('working_day', models.BooleanField(default=True, verbose_name='يوم عمل')),
                ('source', models.CharField(choices=[('auto', 'آلي'), ('manual', 'يدوي')], default='auto', max_length=10, verbose_name='مصدر السجل')),
                ('note', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='sale_sessions.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل الحضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ('-date', 'employee__name'),
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
