# Generated by Django 6.1.1 on 2026-10-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepolicy',
            name='weekend_days',
            field=models.JSONField(blank=True, default=list, help_text='أرقام الأيام بترتيب date.weekday(): 0 الاثنين .. 4 الجمعة .. 6 الأحد. الافتراضي الجمعة', verbose_name='أيام العطلة الأسبوعية'),
        ),
    ]
