# Generated by Django 6.1.1 on 2026-10-01 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancepolicy_weekend_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepolicy',
            name='login_window_end',
            field=models.TimeField(default=datetime.time(9, 0), help_text='بعد هذه الساعة يُحتسب دخولٌ متأخّر', verbose_name='نهاية نافذة الدخول'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='login_window_start',
            field=models.TimeField(default=datetime.time(7, 0), help_text='قبل هذه الساعة يُعدّ الدخول مبكراً (قبل الدوام)', verbose_name='بداية نافذة الدخول'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='logout_window_end',
            field=models.TimeField(default=datetime.time(18, 0), help_text='بعد هذه الساعة يُحتسب العمل إضافياً من لحظة بداية نافذة الخروج', verbose_name='نهاية نافذة الخروج'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='logout_window_start',
            field=models.TimeField(default=datetime.time(16, 0), help_text='قبل هذه الساعة يُحتسب خروجٌ مبكر', verbose_name='بداية نافذة الخروج'),
        ),
    ]
