# Generated by Django 5.2.17 on 2026-09-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('suppliers', '0008_purchaseitem_branch_purchaseitem_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='monthly_sales_target',
            field=models.DecimalField(decimal_places=2, default=0, help_text='صفر يعني بدون هدف', max_digits=15, verbose_name='الهدف الشهري للمبيعات'),
        ),
        migrations.CreateModel(
            name='FabricBranchPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('sale_price_yard', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='سعر بيع الياردة')),
                ('sale_price_roll', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='سعر بيع اللفة')),
                ('min_sale_yard', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الحد الأدنى لسعر بيع الياردة')),
                ('min_sale_roll', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='الحد الأدنى لسعر بيع اللفة')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_prices', to='branches.branch', verbose_name='الفرع')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='suppliers.fabric', verbose_name='القماش')),
            ],
            options={
                'verbose_name': 'سعر قماش في فرع',
                'verbose_name_plural': 'أسعار الأقمشة في الفروع',
                'constraints': [models.UniqueConstraint(fields=('branch', 'fabric'), name='unique_branch_fabric_price')],
            },
        ),
    ]
