# Generated by Django 5.2.17 on 2026-09-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_monthly_sales_target_fabricbranchprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricbranchprice',
            name='piece_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='سعر الطرد/القطعة كاملة في هذا الفرع؛ يُقسَم على 3.5 ليُحتسب سعر بيع الياردة تلقائياً', max_digits=12, null=True, verbose_name='سعر القطعة'),
        ),
    ]
