# Generated by Django 5.2.17 on 2026-09-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=120, verbose_name='اسم التصنيف')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='كود التصنيف')),
                ('is_system', models.BooleanField(default=False, verbose_name='تصنيف أساسي')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تصنيف مصروف',
                'verbose_name_plural': 'تصنيفات المصاريف',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل'), ('card', 'بطاقة'), ('other', 'أخرى')], default='cash', max_length=10, verbose_name='طريقة الدفع')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='branches.branch', verbose_name='الفرع')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='نوع المصروف')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'date'], name='expenses_ex_branch__c0e291_idx'), models.Index(fields=['category', 'date'], name='expenses_ex_categor_9e3535_idx')],
            },
        ),
    ]
