# Generated by Django 5.2.17 on 2026-09-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_monthly_sales_target_fabricbranchprice'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('month', models.DateField(help_text='أول يوم من الشهر', verbose_name='الشهر')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة الميزانية')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='branches.branch', verbose_name='الفرع')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='expenses.expensecategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'ميزانية شهرية',
                'verbose_name_plural': 'الميزانيات الشهرية',
                'ordering': ['-month', 'branch__name', 'category__name'],
                'indexes': [models.Index(fields=['branch', 'month'], name='expenses_ex_branch__cac5a4_idx'), models.Index(fields=['category', 'month'], name='expenses_ex_categor_474304_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'category', 'month'), name='uniq_expense_budget_branch_category_month')],
            },
        ),
    ]
