# Generated by Django 6.1.1 on 2026-09-22 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensebudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='مصروف متكرر'),
        ),
        migrations.AddField(
            model_name='expense',
            name='next_run_date',
            field=models.DateField(blank=True, null=True, verbose_name='موعد الدورة القادمة'),
        ),
        migrations.AddField(
            model_name='expense',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='expenses.expense', verbose_name='المصدر الأصلي للدورة'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recur_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري')], max_length=10, verbose_name='دورة التكرار'),
        ),
    ]
