# Generated by Django 5.2.17 on 2026-09-12 12:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الشريك')),
                ('share_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='نسبة المشاركة %')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='رقم العملية')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('operation_type', models.CharField(choices=[('support', 'دعم'), ('withdraw', 'سحب')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عملية شريك',
                'verbose_name_plural': 'عمليات الشركاء',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='partners.partner', verbose_name='الشريك')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='partners.partneroperation', verbose_name='العملية')),
            ],
            options={
                'verbose_name': 'حركة شريك',
                'verbose_name_plural': 'حركات الشركاء',
                'constraints': [models.UniqueConstraint(fields=('operation', 'partner'), name='unique_movement_per_operation_partner')],
            },
        ),
    ]
