# Generated by Django 5.2.17 on 2026-09-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneroperation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('transfer', 'تحويل بنكي')], default='cash', max_length=10, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='partneroperation',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='السبب'),
        ),
    ]
