# Generated by Django 5.2.17 on 2026-09-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partneroperation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermovement',
            name='movement_type',
            field=models.CharField(choices=[('support', 'دعم'), ('withdraw', 'سحب')], default='support', max_length=10, verbose_name='نوع الحركة'),
        ),
    ]
