# Generated by Django 5.2.17 on 2026-09-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partnermovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneroperation',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='partners.partner', verbose_name='الشريك المسجل عليه العملية'),
        ),
    ]
