# Generated by Django 5.2.17 on 2026-09-26 01:22

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_monthly_sales_target_fabricbranchprice'),
        ('sale_sessions', '0023_restamp_backdated_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('month', models.DateField(help_text='أول يوم من الشهر', verbose_name='الشهر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('paid', 'مدفوع'), ('cancelled', 'ملغى')], default='draft', max_length=10, verbose_name='الحالة')),
                ('payment_method', models.CharField(blank=True, default='', max_length=10, verbose_name='طريقة الصرف')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(blank=True, help_text='فارغ = مسيّر لكل الفروع', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'مسيّر رواتب',
                'verbose_name_plural': 'مسيّرات الرواتب',
                'ordering': ['-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='بدل السكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='بدل النقل')),
                ('other_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='بدلات أخرى')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='ساعات إضافية')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قيمة العمل الإضافي')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='مكافأة')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='عمولة المبيعات')),
                ('absence_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6, verbose_name='أيام الغياب')),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='خصم الغياب')),
                ('late_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='خصم التأخير')),
                ('other_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='خصومات أخرى')),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='يُسجَّل سداداً للسلفة تلقائياً عند الاعتماد', max_digits=12, verbose_name='خصم سلفة')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مصروف')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل')], default='cash', max_length=10, verbose_name='طريقة الصرف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='branches.branch', verbose_name='الفرع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='sale_sessions.employee', verbose_name='الموظف')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun', verbose_name='المسيّر')),
            ],
            options={
                'verbose_name': 'قسيمة راتب',
                'verbose_name_plural': 'قسائم الرواتب',
                'ordering': ['-run__month', 'employee__name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ السلفة')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاريخ السلفة')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل')], default='cash', max_length=10, verbose_name='طريقة الصرف')),
                ('status', models.CharField(choices=[('pending', 'مسودة'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('settled', 'مسددة')], default='pending', max_length=10, verbose_name='الحالة')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ السداد الكامل')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advances', to='branches.branch', verbose_name='الفرع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='sale_sessions.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفة راتب',
                'verbose_name_plural': 'سلف الرواتب',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاريخ السداد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المسدد')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل'), ('deduction', 'خصم من الراتب')], default='deduction', max_length=10, verbose_name='طريقة السداد')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_installments', to='payroll.payslip', verbose_name='قسيمة الراتب')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payroll.salaryadvance', verbose_name='السلفة')),
            ],
            options={
                'verbose_name': 'سداد سلفة',
                'verbose_name_plural': 'سدادات السلف',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='بدل السكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='بدل النقل')),
                ('other_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='بدلات أخرى')),
                ('overtime_hour_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='سعر ساعة العمل الإضافي')),
                ('working_days', models.DecimalField(decimal_places=1, default=Decimal('26'), help_text='يُستخدم في احتساب خصم الغياب (يوم = الراتب الأساسي ÷ الأيام)', max_digits=5, verbose_name='عدد أيام العمل الشهرية')),
                ('effective_from', models.DateField(default=datetime.date.today, verbose_name='سري من تاريخ')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='سري حتى تاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='sale_sessions.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'هيكل راتب',
                'verbose_name_plural': 'هياكل الرواتب',
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['month', 'status'], name='payroll_pay_month_facd9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('month', 'branch'), name='uniq_payroll_run_month_branch'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', '-created_at'], name='payroll_pay_employe_1be0f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='uniq_payslip_run_employee'),
        ),
        migrations.AddIndex(
            model_name='salaryadvance',
            index=models.Index(fields=['employee', 'date'], name='payroll_sal_employe_2c6146_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryadvance',
            index=models.Index(fields=['status', 'date'], name='payroll_sal_status_924771_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['employee', 'effective_from'], name='payroll_sal_employe_898fd1_idx'),
        ),
    ]
