# Generated by Django 5.2.17 on 2026-09-26 01:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='قيمة اليوم'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_hour_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='سعر ساعة العمل الإضافي'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='working_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('26'), help_text='لقطة من الهيكل وقت التوليد', max_digits=5, verbose_name='عدد أيام العمل الشهرية'),
        ),
    ]
