# Generated by Django 6.1.1 on 2026-09-26 11:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payslip_daily_rate_payslip_overtime_hour_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='daily_work_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('9'), help_text='ما زاد على هذا الحد في الوردية يُحتسب عملاً إضافياً (للموظفين المُفعَّل لهم الحضور التلقائي)', max_digits=4, verbose_name='ساعات العمل اليومية'),
        ),
    ]
