# Generated by Django 5.2.17 on 2026-09-11 22:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0003_fabric_yards_per_roll_ledgerentry_receiver_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='المفتاح')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='آخر رقم')),
            ],
            options={
                'verbose_name': 'تسلسل وثيقة',
                'verbose_name_plural': 'تسلسلات الوثائق',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='رقم سند التسوية')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التسوية')),
                ('reason', models.CharField(blank=True, choices=[('damage', 'تلف'), ('loss', 'فقد/نقص'), ('gain', 'زيادة'), ('correction', 'تصحيح جرد')], max_length=20, verbose_name='سبب التسوية')),
                ('direction', models.CharField(choices=[('in', 'إضافة للمخزون'), ('out', 'خصم من المخزون')], max_length=5, verbose_name='نوع التسوية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تسوية مخزون',
                'verbose_name_plural': 'تسويات المخزون',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='رقم جلسة الجرد')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الجرد')),
                ('status', models.CharField(choices=[('open', 'غير منشور'), ('posted', 'منشور'), ('cancelled', 'ملغى')], default='open', max_length=12, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'جلسة جرد',
                'verbose_name_plural': 'جلسات الجرد',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='رقم سند التحويل')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التحويل')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('requested', 'بانتظار الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('completed', 'منفّذ'), ('cancelled', 'ملغى')], default='draft', max_length=12, verbose_name='الحالة')),
                ('requested_by', models.CharField(blank=True, max_length=150, verbose_name='مقدّم الطلب')),
                ('approved_by', models.CharField(blank=True, max_length=150, verbose_name='الموافِق')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الطلب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الموافقة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التنفيذ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تحويل بين المخازن',
                'verbose_name_plural': 'التحويلات بين المخازن',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المخزن')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='كود المخزن')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='الموقع')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('manager_name', models.CharField(blank=True, max_length=150, verbose_name='أمين المخزن')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FabricRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='كود اللفة')),
                ('yards', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الياردات الأصلية')),
                ('remaining_yards', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الياردات المتبقية')),
                ('unit_cost', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='تكلفة الياردة')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('consumed', 'مستنفدة'), ('damaged', 'تالفة')], default='available', max_length=12, verbose_name='الحالة')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='suppliers.fabric', verbose_name='القماش')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'لفة قماش',
                'verbose_name_plural': 'لفات القماش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='رقم سند الاستلام')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الاستلام')),
                ('supplier_receipt_no', models.CharField(blank=True, max_length=50, verbose_name='رقم فاتورة المورد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مُرحّل')], default='draft', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='suppliers.supplier', verbose_name='المورد')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='warehouses.warehouse', verbose_name='المخزن المستلم')),
            ],
            options={
                'verbose_name': 'استلام بضاعة من مورد',
                'verbose_name_plural': 'استلام البضاعة من الموردين',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('rolls_count', models.PositiveIntegerField(default=1, verbose_name='عدد اللفات')),
                ('yards', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي الياردات')),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='سعر الياردة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.fabric', verbose_name='القماش')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouses.goodsreceipt', verbose_name='السند')),
            ],
            options={
                'verbose_name': 'صنف استلام',
                'verbose_name_plural': 'أصناف الاستلام',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('yards', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الياردات')),
                ('rolls_count', models.PositiveIntegerField(default=0, verbose_name='عدد اللفات التقريبي')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouses.stockadjustment', verbose_name='التسوية')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.fabric', verbose_name='القماش')),
            ],
            options={
                'verbose_name': 'صنف تسوية',
                'verbose_name_plural': 'أصناف التسوية',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('system_yards', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد الدفتري')),
                ('counted_yards', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الرصيد الفعلي')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouses.stockcount', verbose_name='الجلسة')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.fabric', verbose_name='القماش')),
            ],
            options={
                'verbose_name': 'صنف جرد',
                'verbose_name_plural': 'أصناف الجرد',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('yards', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الياردات')),
                ('rolls_count', models.PositiveIntegerField(default=0, verbose_name='عدد اللفات التقريبي')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.fabric', verbose_name='القماش')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouses.stocktransfer', verbose_name='التحويل')),
            ],
            options={
                'verbose_name': 'صنف تحويل',
                'verbose_name_plural': 'أصناف التحويل',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouses.warehouse', verbose_name='المخزن المُرسِل'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouses.warehouse', verbose_name='المخزن المُستقبِل'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='warehouses.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='warehouses.warehouse', verbose_name='المخزن'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('movement_type', models.CharField(choices=[('receipt', 'استلام من مورد'), ('transfer_out', 'تحويل صادر'), ('transfer_in', 'تحويل وارد'), ('adjustment_in', 'تسوية إضافة'), ('adjustment_out', 'تسوية خصم'), ('count', 'تسوية جرد'), ('opening', 'رصيد افتتاحي')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية (موقّعة)')),
                ('reference_type', models.CharField(blank=True, max_length=30, verbose_name='المرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('reference_no', models.CharField(blank=True, max_length=40, verbose_name='رقم الوثيقة')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.fabric', verbose_name='القماش')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouses.fabricroll', verbose_name='اللفة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['warehouse', 'date'], name='warehouses__warehou_e8a0ec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fabricroll',
            index=models.Index(fields=['warehouse', 'fabric'], name='warehouses__warehou_61ae21_idx'),
        ),
    ]
