# Generated by Django 5.2.17 on 2026-09-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='branches.branch', verbose_name='الفرع المستلم'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='quantity_mode',
            field=models.CharField(choices=[('yard', 'ياردات'), ('roll', 'لفات')], default='yard', max_length=10, verbose_name='طريقة الكمية'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='branches.branch', verbose_name='الفرع المرتبط'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='rolls_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد اللفات'),
        ),
    ]
