# Generated by Django 5.2.17 on 2026-09-11 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_stocktransfer_to_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouses.warehouse', verbose_name='المخزن المُستقبِل'),
        ),
    ]
