# Generated by Django 5.2.17 on 2026-09-12 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('suppliers', '0004_ledgerentry_branch_ledgerentry_warehouse'),
        ('warehouses', '0003_alter_stocktransfer_to_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='branches.branch', verbose_name='الفرع المستلم'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='suppliers.ledgerentry', verbose_name='قيد الشراء المرتبط'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='warehouses.warehouse', verbose_name='المخزن المستلم'),
        ),
    ]
