# Generated by Django 5.2.17 on 2026-09-12 01:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_fabric_min_stock_alter_fabric_unit'),
        ('warehouses', '0004_goodsreceipt_branch_goodsreceipt_purchase_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الرصيد بعد الحركة'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الرصيد قبل الحركة'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'استلام من مورد'), ('transfer_out', 'تحويل صادر'), ('transfer_in', 'تحويل ياردةد'), ('adjustment_in', 'تسوية إضافة'), ('adjustment_out', 'تسوية خصم'), ('count', 'تسوية جرد'), ('sale', 'مبيعات'), ('opening', 'رصيد افتتاحي')], max_length=20, verbose_name='نوع الحركة'),
        ),
        migrations.CreateModel(
            name='StockOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='رقم سند الرصيد الافتتاحي')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الرصيد الافتتاحي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'رصيد افتتاحي',
                'verbose_name_plural': 'الأرصدة الافتتاحية',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockOpeningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('yards', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الياردات')),
                ('rolls_count', models.PositiveIntegerField(default=1, verbose_name='عدد اللفات')),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='تكلفة الياردة')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.fabric', verbose_name='القماش')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouses.stockopening', verbose_name='السند')),
            ],
            options={
                'verbose_name': 'صنف رصيد افتتاحي',
                'verbose_name_plural': 'أصناف الأرصدة الافتتاحية',
                'ordering': ['id'],
            },
        ),
    ]
