# Generated by Django 5.2.17 on 2026-09-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_stockmovement_balance_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransferitem',
            name='quantity_mode',
            field=models.CharField(choices=[('yard', 'ياردات'), ('roll', 'طاقات')], default='yard', max_length=10, verbose_name='طريقة الكمية'),
        ),
    ]
