# Generated by Django 6.1.1 on 2026-09-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_sessions', '0029_employee_theme'),
        ('warehouses', '0006_alter_stocktransferitem_quantity_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcount',
            name='blind',
            field=models.BooleanField(default=False, verbose_name='جرد مغلق (إخفاء الرصيد الدفتري)'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='sale_sessions.employee', verbose_name='العدّاد'),
        ),
        migrations.AddField(
            model_name='stockcountitem',
            name='note',
            field=models.TextField(blank=True, verbose_name='سبب الفرق'),
        ),
    ]
