# Generated by Django 5.2.17 on 2026-10-06 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_fabricbranchprice_piece_price'),
        ('warehouses', '0007_stockcount_blind_counted_by_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='سبب الإلغاء'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإلغاء'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='ملغي التحويل'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_branch',
            field=models.ForeignKey(blank=True, help_text='يُحدد عند إنشاء التحويل من مخزون الفرع؛ from_warehouse هو مخزن الفرع الداخلي المستخدم للحركة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_out', to='branches.branch', verbose_name='الفرع المُرسِل'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الرفض'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='رافض التحويل'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='reversal_reason',
            field=models.TextField(blank=True, verbose_name='سبب عكس التحويل'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت عكس التحويل'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='reversed_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='عاكس التحويل'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('requested', 'بانتظار الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('completed', 'منفّذ'), ('cancelled', 'ملغى'), ('reversed', 'معكوس')], default='draft', max_length=12, verbose_name='الحالة'),
        ),
    ]
