from django.urls import path
from .analytics_views import (
    BranchPerformanceReportView,
    CashflowReportView,
    EmployeePerformanceReportView,
    FabricProfitabilityReportView,
    InventorySlowReportView,
    PartnerAgingReportView,
    PayrollReportView,
    SalesTrendReportView,
    SummaryReportView,
    SupplierAgingReportView,
)
from .views import (
    BranchReportView,
    CogsReportView,
    CommissionsReportView,
    ExpensesBudgetReportView,
    ExpensesReportView,
    InventoryMovementsReportView,
    InventoryReportView,
    JournalReportView,
    NetDailyReportView,
    ProfitLossReportView,
    SalesReportView,
    SupplierReportView,
)

urlpatterns = [
    path("sales/", SalesReportView.as_view(), name="report-sales"),
    path("expenses/", ExpensesReportView.as_view(), name="report-expenses"),
    path("expenses-budget/", ExpensesBudgetReportView.as_view(), name="report-expenses-budget"),
    path("net-daily/", NetDailyReportView.as_view(), name="report-net-daily"),
    path("suppliers/", SupplierReportView.as_view(), name="report-suppliers"),
    path("branches/", BranchReportView.as_view(), name="report-branches"),
    path("inventory/", InventoryReportView.as_view(), name="report-inventory"),
    path("inventory-movements/", InventoryMovementsReportView.as_view(), name="report-inventory-movements"),
    path("cogs/", CogsReportView.as_view(), name="report-cogs"),
    path("profit-loss/", ProfitLossReportView.as_view(), name="report-profit-loss"),
    path("commissions/", CommissionsReportView.as_view(), name="report-commissions"),
    path("journal/", JournalReportView.as_view(), name="report-journal"),
    # ---------- Reports V2: مؤشرات وتحليلات ----------
    path("summary/", SummaryReportView.as_view(), name="report-summary"),
    path("sales-trend/", SalesTrendReportView.as_view(), name="report-sales-trend"),
    path("branch-performance/", BranchPerformanceReportView.as_view(), name="report-branch-performance"),
    path("employee-performance/", EmployeePerformanceReportView.as_view(), name="report-employee-performance"),
    path("fabric-profitability/", FabricProfitabilityReportView.as_view(), name="report-fabric-profitability"),
    path("inventory-slow/", InventorySlowReportView.as_view(), name="report-inventory-slow"),
    path("supplier-aging/", SupplierAgingReportView.as_view(), name="report-supplier-aging"),
    path("partner-aging/", PartnerAgingReportView.as_view(), name="report-partner-aging"),
    path("cashflow/", CashflowReportView.as_view(), name="report-cashflow"),
    path("payroll/", PayrollReportView.as_view(), name="report-payroll"),
]