# Generated by Django 5.2.17 on 2026-09-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_sender__5ce791_idx',
            old_name='messaging_m_sender__ca4e27_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_receive_33531a_idx',
            old_name='messaging_m_receive_f45464_idx',
        ),
    ]
