# Generated by Django 5.2.17 on 2026-09-16 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_messaging_m_sender__ca4e27_idx_messaging_m_sender__5ce791_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الحذف'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التعديل'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message', verbose_name='الرد على'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to_body',
            field=models.TextField(blank=True, verbose_name='نص الرسالة المُركّبة عليها'),
        ),
    ]
