# Generated by Django 6.1.1 on 2026-09-27 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_fabricbranchprice_piece_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('date', models.DateField(verbose_name='تاريخ الاستلام')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ المستلم')),
                ('method', models.CharField(choices=[('transfer', 'تحويل بنكي'), ('cash', 'نقدي'), ('other', 'أخرى')], default='transfer', max_length=10, verbose_name='طريقة الاستلام')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع التحويل / رقم العملية')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(blank=True, help_text='فارغ = دفعة على الحساب الكلي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_collections', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_collections', to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
            ],
            options={
                'verbose_name': 'دفعة ماكينة بطاقة',
                'verbose_name_plural': 'دفعات ماكينة البطاقة',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['branch', 'date'], name='machine_acc_branch__78df57_idx')],
            },
        ),
    ]
