# Generated by Django 5.2.17 on 2026-09-28 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_fabricbranchprice_piece_price'),
        ('machine_account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinecollection',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'دفعة تسوية', 'verbose_name_plural': 'دفعات التسويات'},
        ),
        migrations.RemoveIndex(
            model_name='machinecollection',
            name='machine_acc_branch__78df57_idx',
        ),
        migrations.AddField(
            model_name='machinecollection',
            name='account',
            field=models.CharField(choices=[('machine', 'حساب الماكينة'), ('bank', 'حساب البنك')], default='machine', help_text='الحساب الذي سدّدته هذه الدفعة', max_length=10, verbose_name='الحساب'),
        ),
        migrations.AddIndex(
            model_name='machinecollection',
            index=models.Index(fields=['account', 'branch', 'date'], name='machine_acc_account_31fd50_idx'),
        ),
    ]
