# Generated by Django 6.1.1 on 2026-09-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_account', '0002_alter_machinecollection_options_and_more'),
        ('suppliers', '0013_ledgerentry_settlement_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecollection',
            name='supplier_payment',
            field=models.OneToOneField(blank=True, help_text='يُملأ تلقائياً عند تسجيل دفعة لمورد من حساب الماكينة أو البنك، فتصير الدفعة مرئيةً في القسم الذي خُصمت منه', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_movement', to='suppliers.ledgerentry', verbose_name='دفعة المورد التي سدّدتها'),
        ),
    ]
