# Generated by Django 5.2.17 on 2026-09-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المورد')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='الدولة')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['name'],
            },
        ),
    ]
