# Generated by Django 5.2.17 on 2026-09-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القماش')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='كود القماش')),
                ('unit', models.CharField(choices=[('yard', 'ياردة'), ('roll', 'لفة')], default='yard', max_length=10, verbose_name='الوحدة الأساسية')),
                ('default_price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='السعر الافتراضي')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل')),
            ],
            options={
                'verbose_name': 'قماش',
                'verbose_name_plural': 'الأقمشة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('entry_type', models.CharField(choices=[('opening', 'رصيد افتتاحي'), ('purchase', 'شراء'), ('payment', 'دفعة'), ('return', 'مرتجع'), ('adjustment', 'تسوية')], max_length=12, verbose_name='نوع القيد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ (موقّع)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='البيان')),
                ('receipt_no', models.CharField(blank=True, max_length=50, verbose_name='رقم السند/الفاتورة')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'كاش'), ('bank_transfer', 'تحويل بنكي')], max_length=15, null=True, verbose_name='طريقة الدفع')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='رقم الحوالة/المرجع البنكي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='suppliers.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'قيد دفتر مورد',
                'verbose_name_plural': 'قيد دفتر الموردين',
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('quantity_yards', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية (ياردة)')),
                ('rolls', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='عدد اللفات')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='سعر الياردة')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الإجمالي')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.ledgerentry', verbose_name='القيد')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='suppliers.fabric', verbose_name='القماش')),
            ],
            options={
                'verbose_name': 'صنف شراء',
                'verbose_name_plural': 'أصناف الشراء',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['supplier', 'date'], name='suppliers_l_supplie_8b8df7_idx'),
        ),
    ]
