# Generated by Django 5.2.17 on 2026-09-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_fabric_ledgerentry_purchaseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='yards_per_roll',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نسبة التحويل بين اللفات والياردات لضمان اتساق الكميات', max_digits=8, null=True, verbose_name='ياردات اللفة الواحدة'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم المستلم'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='rolls',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='عدد اللفات'),
        ),
    ]
