# Generated by Django 5.2.17 on 2026-09-12 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('suppliers', '0003_fabric_yards_per_roll_ledgerentry_receiver_name_and_more'),
        ('warehouses', '0003_alter_stocktransfer_to_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_entries', to='branches.branch', verbose_name='فرع التوريد'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_entries', to='warehouses.warehouse', verbose_name='مخزن التوريد'),
        ),
    ]
