# Generated by Django 5.2.17 on 2026-09-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_ledgerentry_branch_ledgerentry_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='عندما ينخفض رصيد القماش عن هذا الحد يظهر تنبيه نقص في المخزون', max_digits=12, verbose_name='حد التنبيه الأدنى'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='unit',
            field=models.CharField(choices=[('yard', 'ياردة'), ('meter', 'متر'), ('roll', 'لفة')], default='yard', max_length=10, verbose_name='الوحدة الأساسية'),
        ),
    ]
