# Generated by Django 5.2.17 on 2026-09-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_fabric_min_stock_alter_fabric_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='default_price',
            new_name='sale_price_yard',
        ),
        migrations.AddField(
            model_name='fabric',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, verbose_name='الباركود'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='color',
            field=models.CharField(blank=True, max_length=60, verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='composition',
            field=models.CharField(blank=True, max_length=150, verbose_name='التركيبة'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع القماش'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150, verbose_name='الشركة المصنعة'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='min_sale_roll',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='الحد الأدنى لسعر بيع اللفة'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='min_sale_yard',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الحد الأدنى لسعر بيع الياردة'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='بلد المنشأ'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='purchase_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='تكلفة الشراء (ياردة)'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='sale_price_roll',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='سعر بيع اللفة'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='suppliers.supplier', verbose_name='المورد الأساسي'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='weight_gsm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='الوزن (جم/م²)'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='العرض (سم)'),
        ),
    ]
