# Generated by Django 5.2.17 on 2026-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_remove_fabric_default_price_fabric_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='sale_price_yard',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='سعر بيع الياردة'),
        ),
    ]
