# Generated by Django 5.2.17 on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('suppliers', '0007_alter_fabric_sale_price_yard'),
        ('warehouses', '0004_goodsreceipt_branch_goodsreceipt_purchase_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='branches.branch', verbose_name='فرع توريد البند'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='warehouses.warehouse', verbose_name='مخزن توريد البند'),
        ),
    ]