# Generated by Django 5.2.17 on 2026-09-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_purchaseitem_branch_purchaseitem_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='unit',
            field=models.CharField(choices=[('yard', 'ياردة'), ('roll', 'طاقة')], default='yard', max_length=10, verbose_name='الوحدة الأساسية'),
        ),
    ]
