# Generated by Django 5.2.17 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_alter_fabric_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='allow_roll_sale',
            field=models.BooleanField(default=True, help_text='أطفئه لمنع بيع هذا القماش بالطاقة (اللفة) في ورديات البيع', verbose_name='السماح بالبيع بالطاقة'),
        ),
    ]