# Generated by Django 6.1.1 on 2026-09-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_fabric_allow_roll_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='roll_sale_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='خريطة رقم الفرع → (true/false) للتحكم في بيع الطاقة لكل فرع على حدة؛ الفرع غير المذكور يتبع الإعداد العام', verbose_name='البيع بالطاقة حسب الفرع'),
        ),
    ]
