# Generated by Django 5.2.17 on 2026-09-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_fabric_roll_sale_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='piece_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='سعر الطرد/القطعة كاملة؛ يُقسَم على 3.5 ليُحتسب سعر بيع الياردة تلقائياً', max_digits=12, null=True, verbose_name='سعر القطعة'),
        ),
    ]
