# Generated by Django 6.1.1 on 2026-09-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_fabric_piece_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='settlement_account',
            field=models.CharField(blank=True, choices=[('machine', 'حساب الماكينة'), ('bank', 'الحساب البنكي'), ('none', 'لا يخصم من الماكينة ولا البنك')], default='', help_text='إلزامي عند تسجيل دفعة: حساب الماكينة، أو الحساب البنكي، أو لا خصم منهما. يحدّد أي حساب تسوية تنقص حركته قيمة الدفعة', max_length=10, verbose_name='الحساب الذي خُصم منه'),
        ),
    ]
