# Generated by Django 5.2.17 on 2026-09-20 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale_sessions', '0011_provision_employee_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('section', models.CharField(blank=True, default='', max_length=50, verbose_name='القسم')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الإجراء')),
                ('model_name', models.CharField(blank=True, default='', max_length=120, verbose_name='النموذج')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='معرّف السجل')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف السجل')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='العنوان')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='الطريقة')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='المسار')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='sale_sessions.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='audit_audit_employe_74192e_idx'), models.Index(fields=['section', 'timestamp'], name='audit_audit_section_ebc095_idx')],
            },
        ),
    ]
